version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo-test
    ports:
      - 27017:27017
    environment:
      - MONGO_URI=mongodb://mongo-test:27017/test
